version: '3'
services:
  mynode:
    build: 
      context: ./docker
      args:
        - NODE_VERSION=${node_version}
        - ANGULAR_VERSION=${angular_version}
        - APP_NAME=${app_name}
    container_name: mynode
    volumes:
      - ./app:/var/app
      #- /var/app/${app_name}/node_modules/
    command: "/usr/local/bin/ng new ${app_name} --minimal --routing --style scss --skip-git"
